---
# This will download wordpress app

- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/tmp/wordpress-{{ wp_version }}.tar.gz checksum="{{ wp_checksum }}"
  
- name: Extract archive
  ansible.builtin.unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: [--strip-components=1]
